### ISSUE TITLE
Language packs to support various languages.

### ISSUE THREAD

**Issue by sakots** [thenickdude/chickenpaint#25]
This is more of a request than an issue, but I wonder if it would be possible to create a language pack to support the display of various languages.
I was very impressed with the Japanese Oekaki board.
I think it would be good if language packs could be created by people who are familiar with the language.

**Comment by thenickdude** [comment]
Yes, that is possible, are you available to translate ChickenPaint for me if I add support for this?

**Comment by sakots** [comment]
Of course, I'm happy to help. 
There are already people who are translating privately, and I would like to collaborate with them.

For example,
http://ksato0.blog57.fc2.com/blog-entry-325.html
The owner of this site translates personally.
https://pbbs.sakura.ne.jp/cgi/poti002/

**Comment by satopian** [comment]
![image](https://user-images.githubusercontent.com/44894014/118586198-43e61000-b7d5-11eb-80fd-84142b10205c.png)
It can be translated into Japanese.
What I personally thought about translating this time was ...
It means that it is difficult to find the part to be translated.
If I can identify the part to be translated from the beginning, I think it will be easier to translate.
I think that's the case with any language.

**Comment by thenickdude** [comment]
ksato0のsatopianですか？[この日本語訳](http://ksato0.blog57.fc2.com/blog-entry-325.html)をつかってもいいですか？

**Comment by satopian** [comment]
Oh ... ksato is my friend.
The source code translated into Japanese can be found here.
https://raw.githubusercontent.com/satopian/poti-kaini/master/potiboard2/chickenpaint/js/chickenpaint.js
Please use it.
It's a little different from the ksato translation.

**Comment by thenickdude** [comment]
I've posted a draft of the translation here now:

https://github.com/thenickdude/chickenpaint/tree/i18n

It is still waiting for ksato to approve.

This is the language file:

https://github.com/thenickdude/chickenpaint/blob/i18n/js/languages/ja.json

It detects the browser language automatically. You can set it manually instead by setting `language: "ja_JP"` in the options.

![Screen Shot 2021-05-18 at 9 23 17 PM](https://user-images.githubusercontent.com/1921411/118626814-4bcaa200-b81f-11eb-9228-ce895b1f3c0f.png)

**Comment by satopian** [comment]
I made a pull request.
Since ksato does not have a GitHub account, I translated it in consultation with ksato.
In both cases, the English word is "color".
However, the palette for Japanese people to choose colors is the "color picker(カラーピッカー)".
It is easier to understand if the slider that adjusts the amount of color is set to "Color Replenishment(色補充)".
This language pack is
If you translate "color" as "color replenishment(色補充)", the color picker will also be "color replenishment".
Only that point is a little disappointing.
![image](https://user-images.githubusercontent.com/44894014/118644565-e70c4900-b818-11eb-9593-b9b8bdfadf45.png)

**Comment by satopian** [comment]
When I noticed, sakots and satopian were making a pull request for the Japanese translation at the same time.
The translation of sakots is based on the words used in the paint software.
The satopian translation is based on checking the features and comparing them with the various features of the paint software.
I withdrew my pull request because it would be confusing if the two translations were pulled at the same time.
Once the sakots translations have been merged, I would like to fix it further and pull request.

**Comment by thenickdude** [comment]
Thanks, I've merged sakots now

**Comment by sakots** [comment]
satopian and thenickdude,
I'd like to thank you both.

**Comment by satopian** [comment]
Japanese translation of palette name

![image](https://user-images.githubusercontent.com/44894014/118759913-d7d6db00-b8ac-11eb-97a7-8de08999bd70.png)
↑
ツール

![image](https://user-images.githubusercontent.com/44894014/118759965-f2a94f80-b8ac-11eb-8a14-277501d92502.png)
↑
レイヤー

![image](https://user-images.githubusercontent.com/44894014/118760004-048af280-b8ad-11eb-807b-ed0a8b38106a.png)
↑
操作

![image](https://user-images.githubusercontent.com/44894014/118760037-0fde1e00-b8ad-11eb-926a-4ab4dd2d7c96.png)
↑
ツールオプション

![image](https://user-images.githubusercontent.com/44894014/118760081-25ebde80-b8ad-11eb-950f-c43f8875f616.png)
↑
カラーセット

![image](https://user-images.githubusercontent.com/44894014/118760114-3308cd80-b8ad-11eb-9b22-dcc2a98c50f8.png)
↑
テクスチャ

![image](https://user-images.githubusercontent.com/44894014/118760139-3dc36280-b8ad-11eb-9dc9-f4c6ab8eea41.png)
↑
ストローク

![image](https://user-images.githubusercontent.com/44894014/118760165-4b78e800-b8ad-11eb-8f5b-9a7a53f65903.png)
↑
カラー

**Comment by thenickdude** [comment]
Merged to the master branch now, thanks!

**Comment by satopian** [comment]
Thank you for supporting the Japanese lang display of ChickenPaint.
However, there was something I noticed.
Some of the layer masks and menus that are displayed when a clipping layer or layer mask is present are still in English.

![image](https://user-images.githubusercontent.com/44894014/119014734-3b5b2880-b9d3-11eb-9aa7-7629c04c3c0f.png)
![image](https://user-images.githubusercontent.com/44894014/119014767-41e9a000-b9d3-11eb-8dde-5729da8c096a.png)

The text translated into Japanese is as follows.
"Unclip from the layer below" "クリッピング解除"
"Delete mask" "レイヤーマスク削除"
"Disable mask" "レイヤーマスク無効化"
"Enable mask" "レイヤーマスク有効化"
"Apply mask" "レイヤーマスク適用"

"Apply layer mask" "レイヤーマスク適用"
"Delete layer mask" "レイヤーマスク削除"

**Comment by satopian** [comment]
I added a Japanese translation and made a pull request.
![image](https://user-images.githubusercontent.com/44894014/119489668-dfa7eb00-bd96-11eb-9b71-79fbcf7cc4f6.png)
