### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by blurymind** [thenickdude/chickenpaint#6]
Would you be open to the idea of updating the icons and filling in all the missing ones?
(blender, burn, pen, blur,dodge, watercolor)
The missing ones make the app look unfinished

We can take from gimp's color set
https://gitlab.gnome.org/GNOME/gimp/blob/master/icons/Color/color-scalable.svg?expanded=true&viewer=rich

or if you are open we can even use the modernized symbolic set
https://gitlab.gnome.org/GNOME/gimp/blob/master/icons/Symbolic/symbolic-scalable.svg

I can do a PR if you are open to the idea :) 

Do you know any other sets we can borrow from? mypaint and krita also come to mind

Krita's are nicer than gimp's imo
https://github.com/KDE/krita/tree/8d8dc773da21a0357fd4e33e14253d5b962e9ad0/krita/data/preset_icons/tool_icons

and mypaint's
https://github.com/mypaint/mypaint/tree/master/svg

**Comment by thenickdude** [comment]
Last time I looked at these sets they had other missing gaps that would
have left the icon bank just as spotty as it is now, but in different
places. Let me know if you find a complete set!

**Comment by blurymind** [comment]
Would you be open to using kritas icon set? They are more descriptive in how the brushes look and the license is clearly stated as cc 
https://community.kde.org/Krita/Brushes_Preset_Preview

**Comment by thenickdude** [comment]
I cannot imagine how those gigantic detailed icons would still be readable when scaled down to the size used in ChickenPaint.

**Comment by Anteira** [comment]
Hi,

I noticed this issue and being interested in the App I thought I can contribute with my experience as a Graphic/Visual Designer and could make an icon set for Chicken Paint. 

Here is a rough sketch of my idea.

![Chicken_Paint_New_Icon_Set_Sketches](https://user-images.githubusercontent.com/84803593/119545106-58ed1100-bd8a-11eb-830f-b93f807f08b8.jpg)


Please, consider in mind that I am open for ideas.

I would like to have your approval/feedback before I move further to prototyping.

**Comment by thenickdude** [comment]
That would be fantastic actually!

Another icon that would be useful is a "grabbing hand" icon which could be used to grab and pan the canvas.

For future features it would be useful to have a magic wand tool icon and a circular selection tool icon.

I don't think I've seen a Save/Post icon that I've loved the concept of in any icon set I've looked at. This action has to be pretty easily recognised and understood because there needs to be a visually obvious way of figuring out how to finish things up and exit the app, otherwise the user gets trapped within it. This tool is distinct from all the others since it isn't about editing the picture, so needs to not be just "one more of the 30 different tools I could use to edit the pic", because otherwise it becomes impossible to find. 

Also in some Oekaki gallery integrations you can only save-and-exit ("post pic"), they do not support save-and-continue ("save pic"), which is weird and is a nasty surprise for the user if they don't understand. Conversely, for sites that do support multiple saves, we want to encourage the user to save often so they don't accidentally lose their progress. 

Other options I've seen for this icon are the floppy disk save icon (which might not be recognised these days?) and a cloud with an upwards pointing icon ("upload to cloud"). 

It seems really difficult to illustrate this pictorally, and I wonder if it could make sense to keep this one as the sole text button.

**Comment by Anteira** [comment]
Thanks for your feedback :)

I've added some sketches to the icons that you've mentioned.
Again, I've decided to include some options for the magic wand. See description below each one :)

![Chicken_Paint_New_Icon_Sketches_Set_2](https://user-images.githubusercontent.com/84803593/120014423-ef634180-bfd9-11eb-9545-be9263e409b1.jpg)

As for the Save/Post Pic icon, I think it will be better if we have two separate icons. One for "Save", and another for "Post Pic" if you are planning to offer both options (save-and-exit and save-and-continue). For the "Save" (save-and-continue), we could use the floppy disk icon, as it is already established standard. For the other option, that is "Post Pic" I suggest that we can use one of the two icons, shown in the top right corner.

See picture below:

![Chicken_Paint_New_Icon_Sketches_Set_2 1](https://user-images.githubusercontent.com/84803593/120014398-e83c3380-bfd9-11eb-9315-58289a36bf79.jpg)

I think that the one on the **right hand side (2nd one)** works better.

Tell me what you think.

**Comment by thenickdude** [comment]
I like the idea of having two separate save buttons when that is supported (floppy disk + post), it will also provide a visual cue that the "post pic" icon is related to saving (especially if I visually group them together into a little two icon group)

Yeah I like the right-hand design (rectangular picture with an upwards arrow) for the Post Pic icon too!

The lasso design is cute

I think the magic wand design that is successful will depend on how much detail can be packed into the icon size. Tool icons currently display at 32x32 pixels, but on high resolution screens like Macs and phones the icon image can be 64x64 pixels to give extra detail in that same physical space.

**Comment by Anteira** [comment]
I'm glad that we both liked the idea of having two separate icons. Yeah, if you group them together visually in a two icon set I think will be clear enough to the user. 

Yeah, the right-hand design of the Post Pic Icon is much more clear than the rest of the ideas.

I will start prototyping them in Illustrator and afterwards will export them in .SVG and .PNG formats at 32x32 and 64x64 pixels. 
Again, will post them for discussion, so we can decide how to proceed.

Also, I think it will be better if we have a monochrome version and will do a coloured version, just to see how it will look.
I also think that it will be good if we support a "dark theme" interface as this will contribute to the user experience. Having the user to concentrate only on their drawing, without being too distracted by the interface.

**Comment by Anteira** [comment]
Here is a brief look on the icons. I did the full set as we discussed and added some additional hand gesture icons, as I wasn't sure if we had all of them at the moment. 

Some designs differ from my initial sketch. 

For example the "brush", "watercolour" and "pen" icons are a close up of the tip of each. 

<img width="321" alt="Screenshot 2021-06-16 at 16 48 26" src="https://user-images.githubusercontent.com/84803593/122251871-cdffc200-cec2-11eb-95d0-550b58cbece6.png">     <img width="314" alt="Screenshot 2021-06-16 at 16 47 39" src="https://user-images.githubusercontent.com/84803593/122251887-d2c47600-cec2-11eb-8f80-f121b446dafd.png">

<img width="154" alt="Screenshot 2021-06-16 at 16 48 31" src="https://user-images.githubusercontent.com/84803593/122251975-e66fdc80-cec2-11eb-808b-54c31c9bf6d6.png">     <img width="139" alt="Screenshot 2021-06-16 at 16 47 28" src="https://user-images.githubusercontent.com/84803593/122251998-ea9bfa00-cec2-11eb-9ee4-44dd2305a7bf.png">

This way it's more clear which one is being used, otherwise because of their size they might end up looking the same and get confused with the "pencil" icon.

Another different approach compared to the sketch was used on the "hard eraser" and "soft eraser" icons. 

<img width="330" alt="Screenshot 2021-06-16 at 16 47 02" src="https://user-images.githubusercontent.com/84803593/122252260-1a4b0200-cec3-11eb-94be-ee015daefd77.png">     <img width="327" alt="Screenshot 2021-06-16 at 16 47 16" src="https://user-images.githubusercontent.com/84803593/122252282-1d45f280-cec3-11eb-9a7f-63afca47c7ba.png">

I think that is much clearer with this design, when the "hard eraser" has more angular features and the "soft eraser" has more rounded appearance. 

Also the "magic wand" icon has two different interpretations. 

<img width="426" alt="Screenshot 2021-06-16 at 16 48 19" src="https://user-images.githubusercontent.com/84803593/122252699-76158b00-cec3-11eb-990e-1be77fa3948e.png">     <img width="311" alt="Screenshot 2021-06-16 at 16 47 58" src="https://user-images.githubusercontent.com/84803593/122252717-77df4e80-cec3-11eb-996f-e18a19c0c4a3.png">

I think we can keep both and decide later which one works best.

The same goes for the grabbing hand icon. I am not sure if we will need one that looks as if it's grabbing something without forming a fist or not, hence the two different versions.

<img width="216" alt="Screenshot 2021-06-16 at 16 55 23" src="https://user-images.githubusercontent.com/84803593/122253256-e91f0180-cec3-11eb-9307-6c71b8318470.png">     <img width="310" alt="Screenshot 2021-06-16 at 16 55 33" src="https://user-images.githubusercontent.com/84803593/122253282-ef14e280-cec3-11eb-8592-50d553b6f9dd.png">
 

Here is the current design of the icons:

<img width="1058" alt="Current Icons" src="https://user-images.githubusercontent.com/84803593/122250996-094dc100-cec2-11eb-82b4-46b73f8bde24.png">

Here are the three new different versions as discussed: 

**First one in dark grey.** 

<img width="1402" alt="icons-dark_grey" src="https://user-images.githubusercontent.com/84803593/122246401-6cd5ef80-cebe-11eb-88e1-4cfb53fa92c6.png">

<img width="1062" alt="icons-dark_grey(example)" src="https://user-images.githubusercontent.com/84803593/122246495-7cedcf00-cebe-11eb-9794-bfdea9a89794.png">

**Second one in very light grey (for the dark theme).** 

<img width="1387" alt="icons-light_grey" src="https://user-images.githubusercontent.com/84803593/122246545-8a0abe00-cebe-11eb-8b1c-5db35c7a2870.png">

![icons-light_grey(example)](https://user-images.githubusercontent.com/84803593/122246571-9131cc00-cebe-11eb-8b39-9096608ad511.jpg)

**Third one in colour. The colour scheme is not that intense, colour is being used only as an accent to enhance the visual cue for each icon or to group several icons, for example the "stroke", "line", "Bezier curve"  and create a "rectangle" or "circle" icons.** 

<img width="1367" alt="icons-colour" src="https://user-images.githubusercontent.com/84803593/122246626-9d1d8e00-cebe-11eb-97d9-dd926ff1d262.png">

<img width="1060" alt="icons-colour(example)" src="https://user-images.githubusercontent.com/84803593/122246650-a27ad880-cebe-11eb-991f-255c2d90271c.png">

I still need to clean them up a bit and resize them to the boundaries of each Artboard (64x64px), if we need them in SVG format as well. I will prepare a separate folder called "New Icons Design" that will contain all icons (grey, light grey and coloured) in separate PNG image that has all of each category in one file, as well as an SVG file for each separate icon. Will include the Ai file as well for any future reference and adjustments.

I would love to hear your thoughts and suggestions :)

**Comment by thenickdude** [comment]
Those look fantastic, thanks! This will really polish up ChickenPaint!

I think the grayscale versions look best.

The blender icon gets a little unclear at the final display size, maybe the circle can be deleted and the other elements scaled up slightly?

The 100% on the zoom icon isn't legible enough, but this can probably be solved by just different hinting in the vendor renderer rather than by changing the design.

**Comment by Anteira** [comment]
Glad you liked them :)

I'm happy to help polishing up ChickenPaint. I've some other proposals for improvements, but let's finish the icons first. One of them is to create a branding, I want it to look professional and quirky at the same time, so I do have something in mind which I'll share with you shortly.

I too think that the greyscale versions look cleaner compared to the coloured one.

I had the same doubts about the blender Icon. I though that the circle will serve as some kind of unification of all three different "paint" bubbles, but it might be a bit too much as you are saying. I'll follow your advice and will scale them up a bit and remove the inner circle. 

Besides that I think all icons should be scaled up a bit anyway as they are not filling up the space of the 64x64 square, as they should be. I've already started optimising them.

Yeah, that "100%" text on the zoom icon doesn't work well, not quite legible. you could do a different hinting on the vendor render, but I'll do my best to make it a bit more prominent anyway :)

I'll do all mentioned adjustments and will post them shortly :)

**Comment by Anteira** [comment]
Here is an update on the final Icons draft.

It took me a while to try to adjust the "Blend Icon", as just removing the circle has created other issues, like the centre of the three swirls, was not exactly in the middle and also the silhouette looked as if something was wrong. 
See images below:

<img width="288" alt="Screenshot 2021-07-20 at 16 28 51" src="https://user-images.githubusercontent.com/84803593/126369078-8b0a8c63-936d-4190-b717-198881815908.png"><img width="192" alt="Screenshot 2021-07-20 at 18 29 14" src="https://user-images.githubusercontent.com/84803593/126369081-c8f0a0c6-bb8c-41b9-9c09-4f1bbc58f65b.png">

I've decided that I should make a new icon of which every element should have a more circular silhouette.
See image below:

<img width="198" alt="Screenshot 2021-07-20 at 16 28 13" src="https://user-images.githubusercontent.com/84803593/126369585-8b326f10-76ee-4436-96aa-ddd1239a34da.png">

Also another thing that I did is I blew up all of the the icons silhouettes to fully fill the 64x64px of the square size, but then when I tested it the top and down vertical lines were cut off in an awkward way, so I've decided to slightly adjust the inner drawing to be 62x62px.

I've also did another version that has bigger outer margin, so we just need to decide which version looks better.
See image below:

<img width="606" alt="Screenshot 2021-07-20 at 16 27 46" src="https://user-images.githubusercontent.com/84803593/126370552-3f3f35d1-ecd0-4563-9679-c3b84e16ba7b.png">

You can check the examples as shown.
The **first one** is with the icons having a **significantly visible outer margin**.

<img width="1041" alt="Screenshot 2021-07-20 at 15 49 16" src="https://user-images.githubusercontent.com/84803593/126370799-41973b45-68e9-415f-84ea-cdd6da4b67e3.png">

And the second one has just a slight outer margin or you can say even no margin, as it's too close to the actual size.

<img width="1051" alt="Screenshot 2021-07-20 at 16 26 20" src="https://user-images.githubusercontent.com/84803593/126371019-94f3a384-9bcc-469c-b355-7075e6f2d876.png">

I also think that now the 100% magnify icon looks way better. 

Both tests were done with icons exported in PNG format but with 150dpi, as the 72dpi didn't look great. I've tested it both on a regular monitor and a 5K iMac Retina display and both look great.

My personal opinion is that the one with outer margin looks a tat better as we have a bit more white space around each icon and this way it doesn't feel so cramped up. But it depends what we are after I guess.

Please, tell me your thoughts and we can proceed to exporting :)

P.S.: I've started working on the branding as well. Will post some updates next time.

**Comment by satopian** [comment]
I'm a little worried ...
The app dodge icon I know is
The inside of the circle is filled, not the magnifying glass.
![image](https://user-images.githubusercontent.com/44894014/126480324-799907be-b4d7-4750-9af6-0c3f98d5848e.png)

**Comment by Anteira** [comment]
Hi Satopian,

There is no reason to worry about it, this can be easily fixed :)
I get what you mean.
Will send you an update with screenshots this evening!

**Comment by Anteira** [comment]
Here is the updated version of the dodge icon.
I've checked how it was done in Photoshop, and did it in a similar way, just like you mention.

![Photoshop-Dodge-And-Burn](https://user-images.githubusercontent.com/84803593/126530735-6bb3095f-bbe7-4657-9662-330164a7c64d.jpeg)

for some unexplained reason I remembered how it was done years ago, so thanks for spotting that on @satopian :)

<img width="846" alt="Screenshot 2021-07-21 at 18 06 18" src="https://user-images.githubusercontent.com/84803593/126530089-af1bfb84-7e6e-40de-a198-01e4cd012bcf.png">

Here is how it looks in action using icons with outer margin:

<img width="1049" alt="Screenshot 2021-07-21 at 18 02 49" src="https://user-images.githubusercontent.com/84803593/126530160-8559bfb9-4000-4fe9-856c-72eb2d10cc2d.png">

Here is how it looks with icons using no outer margin:

<img width="1049" alt="Screenshot 2021-07-21 at 18 11 03" src="https://user-images.githubusercontent.com/84803593/126530963-d8ed1414-631b-4e14-bde1-009523781b20.png">

Let me hear your thoughts guys :)

**Comment by Anteira** [comment]
Hi Guys, 

Sorry to bother you again with the icons. Just wanted to give a shout to @thenickdude, can you review the icons, so I can upload them? Also, what are the formats that you will need. I guess .PNG, .SVG will make sure that you have them in 64x64px and 32x32px. 

P.S.: I've done some iterations on the branding, and will create a separate issue today.

Thanks!

**Comment by thenickdude** [comment]
Changes look great, yes those are the formats needed. I think I'll need to get those icons installed to review them in-context to see if there needs to be any final tweaks, but I don't anticipate anything.

You can email them to me at n.sherlock@gmail.com if there isn't a good place to post them on GitHub

**Comment by Anteira** [comment]
Hi Guys,

@thenickdude I've attached both the PNG and SVG sets in the Zip Archive.

[ChickenPaint_New_Icons_Set.zip](https://github.com/thenickdude/chickenpaint/files/6977570/ChickenPaint_New_Icons_Set.zip)

You'll see that I've included several resolution versions for each PNG file - 72dpi, 150dpi and 300dpi. all in 32x32px and 64x64px. We've got both separate icons and full icon sheets, depending on what you would prefer to use.

<img width="1656" alt="Screenshot 2021-08-12 at 18 07 46" src="https://user-images.githubusercontent.com/84803593/129238856-268a33ec-22a5-4c9a-8fb0-a120b0fd04db.png">

As for the SVG folder, you can see two folders one for Dark Grey Icons, and Another for the Light Grey Icons. I know that the colour can be easily changed, but decided to include them anyway.

<img width="970" alt="Screenshot 2021-08-12 at 18 08 00" src="https://user-images.githubusercontent.com/84803593/129240127-780004ab-ea27-4dcc-8941-7c9d9ec2410a.png">

Here is some info that might be useful:

Dark Gray Colour                         HEX: 333333
Light Gray Colour                        HEX: E3E3E3
Dark Gray Background Colour   HEX: 4D4D4D
 
This is in case if you decide to do a "Dark Mode" or "Lights Off" version of the UI, which I believe would look quite good too :)

I’m almost done with the last tweaks on the logo design. 
The next improvement will be the widgets UI and widgets tab icons for the mobile version :)
I’ll create a spare issue on GitHub for that.

**Comment by thenickdude** [comment]
Is it okay for me to dual-license the icons under both Creative Commons - Attribution and GPL v3?

**Comment by thenickdude** [comment]
I've updated the example now to include the new icons, please check out the wording in the About box for me too: (you may need to refresh the page / use incognito mode to get the new version)

https://thenickdude.github.io/chickenpaint-example/

The icons look fantastic! The only tweaks I can think of is that I should set up hinting or a pixel font for the "100% zoom" text for the 32px size specifically, since it gets a little blurry, and that on the "rotate canvas" icon, the arrow at the top right is not very readable since it doesn't have much space around it (at both 32 and 64px resolutions)

**Comment by Anteira** [comment]
> Is it okay for me to dual-license the icons under both Creative Commons - Attribution and GPL v3?
> 
> Your request for people to contact you can be included in the About box, but contacting you can't be a requirement of use if we want to be compatible with these licenses.

Of course it is alright to do that! In fact thank you for doing this, I myself was wondering what was the best way to do it, and briefly wrote that note in the "Read_Me" file, as this is my first time contributing to an open source project, besides helping my friends and working full-time as a Creative Designer. I think what you are suggesting is best, of course it is not required to contact me, it was more of a suggestion. 

I've checked the "About" page and I think everything is properly described. 
I have a small request though. 
Can I include those licences under a self publicised repository for the Icons as well? 
Just because I am a new GitHub member and would like to have all my contributions listed on my profile as well.

> I've updated the example now to include the new icons, please check out the wording in the About box for me too: (you may need to refresh the page / use incognito mode to get the new version)
> 
> https://thenickdude.github.io/chickenpaint-example/
> 
> The icons look fantastic! The only tweaks I can think of is that I should set up hinting or a pixel font for the "100% zoom" text for the 32px size specifically, since it gets a little blurry, and that on the "rotate canvas" icon, the arrow at the top right is not very readable since it doesn't have much space around it (at both 32 and 64px resolutions)

I am glad you liked the Icons too. They look quite sharp :) I think that those tweaks are well spotted, definitely will make a big difference. I've spotted that you are using the "Save" icon for Posting Picture, I suppose both this and the other icon with the picture in the middle are interchangeable, but the "Save" icon with the floppy disk relies more on an already built semantic meaning in the user's mind.

**Comment by thenickdude** [comment]
Yeah, you should publish them in a repo I reckon! This way you can make them more discoverable for other people who want to build an art editing tool. If you name your Readme file "Readme.md", GitHub will display the contents of that when you visit the repo page. 

I still haven't fully decided what to do with the save icon, I think I will switch back to the "Post Pic" one.

**Comment by Anteira** [comment]
Thanks Nick for the good advice! Will definitely do that!

As for the save icon, I guess we could do A/B testing. We could run two versions of ChickenPaint, one being with the "Floppy Disk" save icon and another with the "Post Pic" icon. I know that technically the art is being "posted" on the wall and then someone else could work on it if they want to. But let's see what our users think. 

So this is my idea, if you can, could you open an issue on Chicken Smoothie as the creator of ChickenPaint and give the users two versions of the program saying that we want to test some parts of the interface, we want them to navigate freely without projecting our opinions on them, that's why we can't say that we have a preference towards one icon or the other.

After that we can ask them to record their screen, but only while they are using the program. 
They could use OBS - https://obsproject.com/  or we could offer them to use a proper 
UserTesting tool -  https://testersupport.usertesting.com/hc/en-us/articles/115003700731-How-to-Use-the-UserTesting-Screen-Recorder 

We will give them a scenario like that: "Imagine you want to create a new art piece and want it to be posted on the wall" "Can you do this for us?" "Can you elaborate on your decisions while using the interface?"
And then we can see if they can find it the save/post pic icon and if they can recognise one better than the other or they know what both of them are doing.

Or if this can't be done, then we could just give them both versions "Version A" and "Version B", and ask them for each one "Imagine you've created the greatest art piece ever! How can you post your art on the wall?", "Can you explain your steps as 1, 2, 3. etc. while describing each step thoroughly including which icons you've clicked on".

This might give us some insight. I know it might sound like a lot of work. But if the whole testing and screen recording is a bit too complicated then we could do what I mentioned above.

This will be very helpful and could determine which icon is best!

Would love to hear what are your thought on this!

**Comment by thenickdude** [comment]
@Anteira I've published your new toolbar icon set to NPM now in version 0.4.0. I'll see how feedback goes on the "floppy disk" save icon.
